// Generated by scripts/build-cypher-layouts.py.
window.VERSUS_CYPHER_LAYOUTS = Object.freeze({
  "Akitash": {
    "baseline": 275.0,
    "bounds": [
      18,
      19,
      198,
      275
    ],
    "canvas": [
      235,
      300
    ],
    "cardCenterX": 92.66
  },
  "AncientOne": {
    "baseline": 248.0,
    "bounds": [
      44,
      51,
      220,
      248
    ],
    "canvas": [
      267,
      300
    ],
    "cardCenterX": 132.28
  },
  "Aralass": {
    "baseline": 270.0,
    "bounds": [
      25,
      72,
      379,
      270
    ],
    "canvas": [
      406,
      300
    ],
    "cardCenterX": 174.3
  },
  "Buff": {
    "baseline": 242.5,
    "bounds": [
      42,
      55,
      245,
      244
    ],
    "canvas": [
      300,
      300
    ],
    "cardCenterX": 147.75
  },
  "Calfire": {
    "baseline": 284.0,
    "bounds": [
      38,
      31,
      270,
      284
    ],
    "canvas": [
      284,
      300
    ],
    "cardCenterX": 126.7
  },
  "Chesare": {
    "baseline": 261.0,
    "bounds": [
      33,
      28,
      379,
      261
    ],
    "canvas": [
      424,
      300
    ],
    "cardCenterX": 193.56
  },
  "Chonk": {
    "baseline": 273.0,
    "bounds": [
      10,
      31,
      241,
      273
    ],
    "canvas": [
      251,
      300
    ],
    "cardCenterX": 141.73
  },
  "Crescient": {
    "baseline": 226.0,
    "bounds": [
      25,
      2,
      218,
      230
    ],
    "canvas": [
      235,
      300
    ],
    "cardCenterX": 124.56
  },
  "Dandeleon": {
    "baseline": 284.0,
    "bounds": [
      32,
      1,
      418,
      293
    ],
    "canvas": [
      425,
      300
    ],
    "cardCenterX": 210.06
  },
  "Dioxic": {
    "baseline": 265.0,
    "bounds": [
      56,
      39,
      246,
      265
    ],
    "canvas": [
      300,
      300
    ],
    "cardCenterX": 151.78
  },
  "Emberion": {
    "baseline": 278.0,
    "bounds": [
      60,
      17,
      334,
      281
    ],
    "canvas": [
      424,
      300
    ],
    "cardCenterX": 233.81
  },
  "Espiritu": {
    "baseline": 278.25,
    "bounds": [
      30,
      13,
      230,
      290
    ],
    "canvas": [
      232,
      300
    ],
    "cardCenterX": 120.53
  },
  "Ethlectric": {
    "baseline": 283.5,
    "bounds": [
      3,
      0,
      226,
      290
    ],
    "canvas": [
      229,
      300
    ],
    "cardCenterX": 114.5
  },
  "Flexseed": {
    "baseline": 278.0,
    "bounds": [
      5,
      46,
      194,
      278
    ],
    "canvas": [
      227,
      300
    ],
    "cardCenterX": 105.51
  },
  "HokkaidoWave": {
    "baseline": 283.0,
    "bounds": [
      10,
      9,
      306,
      283
    ],
    "canvas": [
      318,
      300
    ],
    "cardCenterX": 135.24
  },
  "Jawsome": {
    "baseline": 253.0,
    "bounds": [
      21,
      125,
      312,
      300
    ],
    "canvas": [
      322,
      300
    ],
    "cardCenterX": 128.4
  },
  "Kamakasu": {
    "baseline": 291.0,
    "bounds": [
      8,
      6,
      373,
      297
    ],
    "canvas": [
      380,
      300
    ],
    "cardCenterX": 194.65
  },
  "Metadash": {
    "baseline": 263.0,
    "bounds": [
      42,
      4,
      300,
      263
    ],
    "canvas": [
      361,
      300
    ],
    "cardCenterX": 195.21
  },
  "Nyx": {
    "baseline": 253.25,
    "bounds": [
      0,
      0,
      300,
      300
    ],
    "canvas": [
      300,
      300
    ],
    "cardCenterX": 146.69
  },
  "Octopunch": {
    "baseline": 285.0,
    "bounds": [
      16,
      9,
      309,
      292
    ],
    "canvas": [
      314,
      300
    ],
    "cardCenterX": 143.91
  },
  "Ohwail": {
    "baseline": 252.5,
    "bounds": [
      28,
      21,
      336,
      276
    ],
    "canvas": [
      360,
      300
    ],
    "cardCenterX": 164.38
  },
  "Oritori": {
    "baseline": 236.5,
    "bounds": [
      86,
      24,
      346,
      261
    ],
    "canvas": [
      424,
      300
    ],
    "cardCenterX": 224.18
  },
  "Rycelium": {
    "baseline": 294.0,
    "bounds": [
      15,
      40,
      290,
      294
    ],
    "canvas": [
      300,
      300
    ],
    "cardCenterX": 149.52
  },
  "Shibachu": {
    "baseline": 274.0,
    "bounds": [
      0,
      36,
      424,
      276
    ],
    "canvas": [
      424,
      300
    ],
    "cardCenterX": 207.79
  },
  "Snek": {
    "baseline": 286.0,
    "bounds": [
      17,
      3,
      327,
      298
    ],
    "canvas": [
      406,
      300
    ],
    "cardCenterX": 208.46
  },
  "Somnowing": {
    "baseline": 239.0,
    "bounds": [
      90,
      31,
      424,
      281
    ],
    "canvas": [
      533,
      300
    ],
    "cardCenterX": 258.18
  },
  "Velocirock": {
    "baseline": 270.0,
    "bounds": [
      12,
      28,
      279,
      270
    ],
    "canvas": [
      300,
      300
    ],
    "cardCenterX": 146.2
  },
  "Voxelion": {
    "baseline": 276.0,
    "bounds": [
      0,
      0,
      300,
      300
    ],
    "canvas": [
      300,
      300
    ],
    "cardCenterX": 145.02
  },
  "Xaldin": {
    "baseline": 271.25,
    "bounds": [
      4,
      19,
      293,
      280
    ],
    "canvas": [
      327,
      300
    ],
    "cardCenterX": 148.91
  }
});
