"""Measure animated Cypher transparency for consistent raft placement.

Requires Pillow. Originals stay untouched; this writes renderer metadata only.
"""

import json
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets" / "cyphers"
OUTPUT = ROOT / "renderer" / "cypher-layouts.js"
ALPHA_THRESHOLD = 32

# Named art-direction exceptions can live here without touching runtime code.
# raftZoom, x, and y affect the raft; zoom and cardX affect the collectible card.
TUNING = {
    "Akitash": {"raftZoom": 0.70},
    "Aralass": {"raftZoom": 1.30},
    "Buff": {"raftZoom": 0.70},
    "Chonk": {"y": 13},
    "Emberion": {"x": -7},
    "Kamakasu": {"raftZoom": 1.30},
    "Nyx": {"raftZoom": 1.50},
    "Shibachu": {"raftZoom": 1.50},
    "Somnowing": {"raftZoom": 1.20},
    "Xaldin": {"y": 20},
}


def percentile(values, amount):
    ordered = sorted(values)
    position = (len(ordered) - 1) * amount
    low = int(position)
    high = min(low + 1, len(ordered) - 1)
    blend = position - low
    return ordered[low] * (1 - blend) + ordered[high] * blend


def visible_bbox(frame):
    alpha = frame.convert("RGBA").getchannel("A")
    solid = alpha.point(lambda value: 255 if value > ALPHA_THRESHOLD else 0)
    return solid.getbbox()


def visual_center_x(frame):
    alpha = frame.convert("RGBA").getchannel("A")
    solid = alpha.point(lambda value: 255 if value > ALPHA_THRESHOLD else 0)
    projection = solid.resize((solid.width, 1), Image.Resampling.BOX)
    weights = list(projection.get_flattened_data())
    total = sum(weights)
    if total == 0:
        return frame.width / 2
    return sum((index + 0.5) * weight for index, weight in enumerate(weights)) / total


def measure(path):
    image = Image.open(path)
    union = None
    bottoms = []
    visual_centers_x = []

    for frame_index in range(image.n_frames):
        image.seek(frame_index)
        bbox = visible_bbox(image)
        if bbox is None:
            continue
        left, top, right, bottom = bbox
        bottoms.append(bottom)
        visual_centers_x.append(visual_center_x(image))
        union = bbox if union is None else (
            min(union[0], left),
            min(union[1], top),
            max(union[2], right),
            max(union[3], bottom),
        )

    if union is None:
        union = (0, 0, image.width, image.height)
        bottoms = [image.height]
        visual_centers_x = [image.width / 2]

    return {
        "canvas": [image.width, image.height],
        "bounds": list(union),
        "baseline": round(percentile(bottoms, 0.75), 2),
        "cardCenterX": round(percentile(visual_centers_x, 0.5), 2),
    }


def main():
    layouts = {}
    for path in sorted(SOURCE.glob("*.gif")):
        layout = measure(path)
        layout.update(TUNING.get(path.stem, {}))
        layouts[path.stem] = layout
    payload = json.dumps(layouts, indent=2, sort_keys=True)
    OUTPUT.write_text(
        "// Generated by scripts/build-cypher-layouts.py.\n"
        f"window.VERSUS_CYPHER_LAYOUTS = Object.freeze({payload});\n",
        encoding="utf-8",
    )
    print(f"measured {len(layouts)} Cyphers -> {OUTPUT}")


if __name__ == "__main__":
    main()
